apiVersion: v1
kind: Pod
metadata:
  name: python-test-pod
  namespace: my-namespace
spec:
  containers:
  - name: python-client
    image: python:3.9-alpine
    command: ["/bin/sh", "-c", "pip install redis && while true; do sleep 3600; done"] # avoid pod terminating
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: conda-test-pod
  namespace: my-namespace
spec:
  containers:
  - name: conda-container
    image: continuumio/miniconda3
    command:
      - "/bin/bash"
      - "-c"
      - |
        conda create -n dev python=3.9
        source activate dev
        conda install -c conda-forge pandas pyarrow 
        python -m pip install redis
        while true; do sleep 3600; done
        echo "Conda environment created and packages installed. You can now run your application."
    # Add additional settings like volume mounts, environment variables, etc. if needed
  restartPolicy: Never
