apiVersion: v1
kind: Pod
metadata:
  name: python-test-pod
  namespace: my-namespace
spec:
  containers:
  - name: python-client
    image: python:3.9-alpine
    command: ["/bin/sh", "-c", "pip install redis && while true; do sleep 3600; done"] # avoid pod terminating
  restartPolicy: Never
